import "./PopupModal.cy"
import "./AlertBox.cy"
import "./BarChart.cy"
import "./CompanyList.cy"
import "./ContactUs.cy"
import "./CreateCompany.cy"
import "./CreateUser.cy"
import "./DeleteButton.cy"
import "./DeleteModal.cy"
import "./Form.cy"
import "./FullScreen.cy"
import "./UploadCompanyLogo.cy"
import "./LoginForm.cy"
import "./MaterialForm.cy"
import "./ReloadToSamePage.cy"
import "./ResetPassword.cy"
import "./SideMenuScroll.cy"
import "./UserList.cy"

// import "./KpiSummary.cy"
// import "./MeterForm.cy"

